### ISSUE TITLE
大佬，appletv版本计划什么时候上线呀

### ISSUE THREAD

**Issue by chneez** [Kimentanm/aptv#1]
rt

**Comment by Kimentanm** [comment]
计划是先开发mac版本的，如果AppleTV的呼声很高的话，可能会先开发ATV版本的
放心吧，时间不会太长

**Comment by wq369641177** [comment]
等tv版

**Comment by Kimentanm** [comment]
tv版已上线Testflight，可以加TG群，不定期开放测试
![image](https://user-images.githubusercontent.com/25970284/175477295-1243d662-6c47-4577-ab00-9718596821f9.png)
