### ISSUE TITLE
MacOS 11.7.10 crash

### ISSUE THREAD

**Issue by kenck-ice** [Kimentanm/aptv#100]
更新了aptv 1.3.0后发现mac 11.7.10系统上无法正常打开app了

Termination Reason:    DYLD, [0x1] Library missing
 
Application Specific Information:
dyld: launch, loading dependent libraries
 
Dyld Error Message:
  dyld: Using shared cache: 3694F5E4-3E85-3CD5-A2B0-534E2DFC1355
Library not loaded: /System/Library/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
  Referenced from: /Applications/APTV.app/Contents/MacOS/APTV
  Reason: image not found

**Comment by Kimentanm** [comment]
macOS11有一些兼容性问题，正在解决中

**Comment by Kimentanm** [comment]
已在APTV for macOS 1.3.1版本中解决了这个问题

**Comment by kenck-ice** [comment]
刚测试可用了，多谢!
