### ISSUE TITLE
节目单在 tv 版不可用

### ISSUE THREAD

**Issue by flyhh008** [Kimentanm/aptv#102]
我的手机和 电视 在相同 wifi 下，都是用的默认 epg，手机上 cctv1 节目单都正常，电视上就没有，只是精彩节目。请帮忙解决，谢谢

**Comment by Kimentanm** [comment]
您好，请告知tv上用的直播源是哪一个？

**Comment by flyhh008** [comment]
> 您好，请告知tv上用的直播源是哪一个？

是的 都是同一个直播文件

**Comment by Kimentanm** [comment]
我问的是具体是哪一个直播源，而不是问是不是同一个直播源

**Comment by Kimentanm** [comment]
App的设置-EPG中填写的节目单地址是什么？
看看与手机上是否有所不同，如果不一样，可以修改成一样的
修改完之后，请将设置列表滑动到最底部，点击退出App然后重新打开App

**Comment by flyhh008** [comment]
你好：
       epg里面就是填的app自带的三个，我们没改，这个问题也可能跟epg不稳定有关系，手机app也不是每次都能正确显示节目单。
       还有一个问题咨询一下，tv版在有节目单，支持回放的前提下，有遥控器怎么操作节目快进或者调进度啊，不太会操作。

谢谢



***@***.***
 
发件人： Kimen
发送时间： 2024-10-07 17:52
收件人： Kimentanm/aptv
抄送： flyhh008; Author
主题： Re: [Kimentanm/aptv] 节目单在 tv 版不可用 (Issue #102)
App的设置-EPG中填写的节目单地址是什么？
看看与手机上是否有所不同，如果不一样，可以修改成一样的
修改完之后，请将设置列表滑动到最底部，点击退出App然后重新打开App

**Comment by Kimentanm** [comment]
1. APTV在AppleTV上默认的EPG一直都只有一个，如果显示的是三个，那么你肯定有修改过。确实会有epg不稳定的情况发生
2. 目前AppleTV上的APTV仅支持遥控器左右按键的快进和快退，暂不支持拖拽进度条的快进。不过如果你有iPhone的，当AppleTV在播放回放的时候，可以通过iPhone锁屏页面的进度条进行拖拽快进

![image](https://github.com/user-attachments/assets/4e66fb25-54ad-4369-b51e-95a30a1d9a30)

**Comment by flyhh008** [comment]
好的，谢谢



***@***.***
 
发件人： Kimen
发送时间： 2024-10-08 09:52
收件人： Kimentanm/aptv
抄送： flyhh008; Author
主题： Re: [Kimentanm/aptv] 节目单在 tv 版不可用 (Issue #102)
APTV在AppleTV上默认的EPG一直都只有一个，如果显示的是三个，那么你肯定有修改过。确实会有epg不稳定的情况发生
目前AppleTV上的APTV仅支持遥控器左右按键的快进和快退，暂不支持拖拽进度条的快进。不过如果你有iPhone的，当AppleTV在播放回放的时候，可以通过iPhone锁屏页面的进度条进行拖拽快进
image.png (view on web)
