### ISSUE TITLE
自己抓的rtsp直播源，可以回看，但是在回看界面拖动进度条画面会卡死

### ISSUE THREAD

**Issue by sean-0925** [Kimentanm/aptv#103]

**Comment by Kimentanm** [comment]
这个问题已在tvOS和macOS版本中修复，iOS节后也会更新

**Comment by sean-0925** [comment]
> 这个问题已在tvOS和macOS版本中修复，iOS节后也会更新
Appletv更新至1.3.3 问题依旧，可能是我的源有问题吧，但iptv盒子就没这个问题，好奇怪

**Comment by Kimentanm** [comment]
不是你的源的问题，1.3.3还是有点问题，目前已在测试版中修复，会尽快更新
