### ISSUE TITLE
TV端回放不能调整进度，会直接卡住。ios端没有问题。

### ISSUE THREAD

**Issue by jq88kazze** [Kimentanm/aptv#104]
这是其中一个直播源http://ott.js.chinamobile.com/PLTV/3/224/3221227675/index.m3u8
TV端回放可以，但是不能调整进度，一动就卡住无法加载。

**Comment by Kimentanm** [comment]
这个频道地址应该是移动内网的吧，我无法访问

**Comment by Kimentanm** [comment]
找到可以复现问题的频道链接了，会尽快修复

**Comment by Kimentanm** [comment]
该问题已在测试版中修复，若需要测试可留下邮箱，我来发送测试邀请 @jq88kazze

**Comment by Kimentanm** [comment]
TV端新版本已更新
