### ISSUE TITLE
bug: White Line Still Appearing on the Top of the Screen (1.3.3)

### ISSUE THREAD

**Issue by dextermo01** [Kimentanm/aptv#106]
![Screenshot 2024-10-04 at 12 10 40 PM](https://github.com/user-attachments/assets/2994f161-d0af-45dc-86cf-db0ce7d3c17a)

System Version: macOS Sonoma 14.7 (23H124)
App Version: APTV for macOS 1.3.3 (MAS)
Display: External 1080p display

I noticed in the "What's New" section of the Mac App Store that the update log mentioned "completely fixes the problem of a white bar appearing at the top when in full screen mode." However in actual use, there is still a white line at the top (as shown in the screenshot).

**Comment by Kimentanm** [comment]
What is the model of mac device you are currently using?
Have you ever tried to double-click the screen to enter the full screen?

**Comment by dextermo01** [comment]
Mac model: A2251 Intel MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

I entered full screen by clicking the green dot button. Double-clicking will only zoom the window. 

![Screenshot 2024-10-04 at 7 07 55 PM](https://github.com/user-attachments/assets/a14b615e-53f2-429e-92e0-b162d1e6bb44)

**Comment by Kimentanm** [comment]
Double-clicking the playing video page will also enter the full screen, instead of double-clicking the green button

**Comment by dextermo01** [comment]
You're right! It works. The white line did not appear this time when I double-clicked the video area to enter full screen. 

It's weird that the white line will appear after the information pad and control buttons fade out when clicking the green button to enter full screen. Still a bug should this be called?

**Comment by Kimentanm** [comment]
It's a bug, but it doesn't work on my macbookpro16, and the white line doesn't appear at the top of the screen when I use the green button or double-click on the screen.
It is recommended that you double-click the full screen, which will be very convenient.
