### ISSUE TITLE
4k 菁彩源无法播放的问题

### ISSUE THREAD

**Issue by hainru** [Kimentanm/aptv#109]

**Comment by hainru** [comment]
aptv 官方 GitHub 主页里提供的测试源，其中 cctv 菁 4k 彩分类下的几个频道，会有几个问题：
1. 几个 4k 源添加到 自定义 m3u 文件里后，再上传到 apple tv  客户会无法正常加载（刚添加时没事，一般第二天使用时会出现无法加载）。
2. 但不从 自定义 m3u  文件里打开，只从客户端收藏功能中打开，却一直可以正常播放，很奇怪。
3. 这几个源播放的时候，会有偶发掉帧卡顿问题，也是 appletv 客户端。
附出现过以上问题的，其中一个 4k 源：http://148.135.93.213:81/live.php?id=CCTV4K-av3a
aptv 官方 Github  页提供的测试源地址：https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u

**Comment by Kimentanm** [comment]
你说的问题是因为AppleTV的app是最新版，而手机app不是最新版导致的
更新手机和电视的App到最新版本，然后刷新配置就可以了
播放掉帧卡顿，请关闭反交错功能

**Comment by Kimentanm** [comment]
手机App最新版是1.3.12
电视App对新版是1.3.6

**Comment by hainru** [comment]
以上问题更新后仍然存在，反交错功能一直是关的。谢谢。

**Comment by Kimentanm** [comment]
菁彩声的频道的Uid参数官方一直在更换，所以经常会播放不了
请及时更新直播源，另外这几个频道不要收藏，一定要在配置内播放

**Comment by hainru** [comment]
> 菁彩声的频道的Uid参数官方一直在更换，所以经常会播放不了 请及时更新直播源，另外这几个频道不要收藏，一定要在配置内播放

明白了，谢谢
