### ISSUE TITLE
直播源如何设置回看？

### ISSUE THREAD

**Issue by brmysss** [Kimentanm/aptv#110]
[(6) Docker 超强进阶！手把手部署 AllInOne，永久电视直播+自动更新，秒切换爽翻天！ - YouTube](https://www.youtube.com/watch?v=a6L-fDrJxag) 
我根据这个教程部属获得了直播源地址：http://192.168.10.2:35455/tv.m3u
但是在APTV里似乎无法进行回看，我该如何设置？
<img width="317" alt="image" src="https://github.com/user-attachments/assets/0657587f-1463-4fba-8a5c-d04e2caacb61">

**Comment by Kimentanm** [comment]
没听过肥羊的allinone可以回看啊，你确定这个源支持回看？
