### ISSUE TITLE
报一个bug，apple tv使用aptv，刚开始网络显示ipv6，用一段时间会自动变成ipv4

### ISSUE THREAD

**Issue by luii2020** [Kimentanm/aptv#112]
报一个bug，apple tv使用aptv，刚开始网络显示ipv6，用几天时间会自动变成ipv4，然后退出aptv，再进入仍然是ipv4，就是说所有ipv6的源都不能看，只有重启apple tv才会正常显示ipv6，iphone版本是不会这样的，另外我已经买会员

**Comment by Kimentanm** [comment]
APTV上的IPv4和IPv6只是针对当前设备当前网络的一个检测，显示IPv4是当前设备没有IPv6地址，与APTV软件本身无关
重启AppleTV之后，重新连接了网络，重新获取到了新的IPv6地址，就又可以播放IPv6的频道
所以这不是APTV的bug
