### ISSUE TITLE
不支持非m3u结尾的链接

### ISSUE THREAD

**Issue by gloobean** [Kimentanm/aptv#14]
APP非常好用，但是不支持非m3u结尾但实际是m3u格式的订阅链接，比如https://pastebin.com/raw/jiWXJjz4

**Comment by Kimentanm** [comment]
收到，下个版本将不会判断链接后缀，只判断文件内容是否符合m3u规范

**Comment by gloobean** [comment]
收到，感谢作者，期待Apple TV版上线

**Comment by MiracleXYZ** [comment]
Same issue here. `m3u8` urls with query strings are not showing up.
e.g. https://raw.githubusercontent.com/moxun33/real-url/master/data/bilibili.m3u

**Comment by MiracleXYZ** [comment]
> > Same issue here. `m3u8` urls with query strings are not showing up. e.g. https://raw.githubusercontent.com/moxun33/real-url/master/data/bilibili.m3u
> 
> I tried this url and it worked on my phone Please check your network can parse `raw.githubusercontent.com` DNS correctly. If you can't visit this url, please use https://cdn.jsdelivr.net/gh/moxun33/real-url/data/bilibili.m3u instead

It's just a network issue and changing to `jsdelivr` works. Thanks a lot!

**Comment by Kimentanm** [comment]
已修改，请见build 0.0.1(13)
