### ISSUE TITLE
后缀不是m3u实际内容为m3u的文件不能播放

### ISSUE THREAD

**Issue by zyjia** [Kimentanm/aptv#19]
有些远程接口文件实际内容是m3u,因为后缀不是无法播放，希望能支持。

**Comment by Kimentanm** [comment]
这个问题已经解决过了呀，[Issue/14(不支持非m3u结尾的链接)](https://github.com/Kimentanm/aptv/issues/14)
如果你的链接无法识别，可以通过邮箱（[Kimentanm@gmail.com](Kimentanm@gmail.com)）把链接发给我来测试一下

**Comment by zyjia** [comment]
> 这个问题已经解决过了呀，[Issue/14(不支持非m3u结尾的链接)](https://github.com/Kimentanm/aptv/issues/14) 如果你的链接无法识别，可以通过邮箱（[Kimentanm@gmail.com](Kimentanm@gmail.com)）把链接发给我来测试一下

不好意思，我这里无法更新版本，提示当前仅支持m3u链接,我的地址是https://pastebin.com/raw/EsjqkNjB

**Comment by Kimentanm** [comment]
我这边添加了一下是可以的，一共849个频道，请问您是在Testflight中看不到APTV的App了吗？
![1751651994030_ pic](https://user-images.githubusercontent.com/25970284/167285930-c44789ce-fd05-4872-abd3-5ba3355e56e7.jpg  
![1761651994175_ pic_hd](https://user-images.githubusercontent.com/25970284/167285981-a98a6f5b-5906-44d8-b4ab-45dc517a3b1b.jpg)
)

**Comment by zyjia** [comment]
> 我这边添加了一下是可以的，一共849个频道，请问您是在Testflight中看不到APTV的App了吗？ ![1751651994030_ pic](https://user-images.githubusercontent.com/25970284/167285930-c44789ce-fd05-4872-abd3-5ba3355e56e7.jpg ![1761651994175_ pic_hd](https://user-images.githubusercontent.com/25970284/167285981-a98a6f5b-5906-44d8-b4ab-45dc517a3b1b.jpg) )

是的，Testflight显示没有APP可供测试。

**Comment by Kimentanm** [comment]
之前TF链接出过一点问题，不过我刚看TF测试组人员已经满了，等我清除一些已不再测试的测试人员后，在这个issue下通知您
