### ISSUE TITLE
TF内测组邀请，名额有限，请在下方回复邮箱

### ISSUE THREAD

**Issue by Kimentanm** [Kimentanm/aptv#21]
> 请不要回复除邮箱以外的其他内容，发了邮箱之后请注意查收邀请链接~

> 注意: 极少使用或者长时间停留低版本将会被请出测试组

> 感谢您的测试~

**Comment by WSL33099** [comment]
wsl330099@gmail.com

**Comment by Jamie0818** [comment]
927862800@qq.com

**Comment by lvminghan44** [comment]
lvminghan44@gmail.com

**Comment by wujunsong521** [comment]
799515203@qq.com

**Comment by wujunsong521** [comment]
799515203@qq.com

**Comment by bxsyysd** [comment]
xiaop0512@gmail.com

**Comment by Jsbox3** [comment]
3689860@gmail.com

**Comment by a136749172** [comment]
liuyu136749172@gmail.com

**Comment by HjiF** [comment]
lee_fyt@icloud.com

**Comment by hailang8888** [comment]
9672659@qq.com

**Comment by Sumuge** [comment]
kiad1412@126.com

**Comment by lvminghan44** [comment]
lminghan9494@g.ucla.edu

**Comment by Morra713** [comment]
86661381@qq.com

**Comment by fumeng-p** [comment]
ll8765889@163.com

**Comment by uswfz** [comment]
unitedstatesweifuzhong@gmail.com

**Comment by fsq190818** [comment]
fpc190916@163.com

**Comment by CodeApe-Xiaoyin** [comment]
2751665677@qq.com

**Comment by hailang8888** [comment]
373705414@qq.com

**Comment by fsq190818** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Morra713** [comment]
jiajia222514@gmail.com

**Comment by qiuyu0830** [comment]
qiuyu0830@vip.qq.com

**Comment by chen66688** [comment]
chen168@live.com

**Comment by Wenchi123** [comment]
617676853@qq.com

**Comment by yunya1122** [comment]
1720672772@qq.com

**Comment by daf625796117** [comment]
625796117@qq.com

**Comment by yunya1122** [comment]
***@***.***





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wenchi123 ***@***.***&gt;
发送时间: 2022年5月12日 14:02
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: yunya1122 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)

**Comment by wangte0109** [comment]
2464854171@qq.com

**Comment by wangte0109** [comment]
260020005@qq.com

**Comment by shoujiqiyuan** [comment]
wuweiscript@gmail.com

**Comment by uswfz** [comment]
chinaweifuzhong@gmail.com

**Comment by jokerwhile** [comment]
jokerwhile33@gmail.com

**Comment by lululubo** [comment]
zcy188157@gmail.com🌹

**Comment by Krew1nd** [comment]
krewind1216@gmail.com

**Comment by Tan-Xi** [comment]
420771353@qq.com

**Comment by NoEggEgg** [comment]
i@ashi.im

**Comment by gerrampard** [comment]
scottuk2020@gmail.com

**Comment by louis562** [comment]
mvy@live.com

**Comment by Wenchi123** [comment]
。。。





------------------ 原始邮件 ------------------
发件人: louis562 ***@***.***&gt;
发送时间: 2022年5月12日 14:19
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: Wenchi123 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 
***@***.***

**Comment by Tan-Xi** [comment]
thy420771353@gmail.com

**Comment by a2272000716** [comment]
a2272000716@gmail.com

**Comment by whp2220** [comment]
whp222@outlook.com

**Comment by shoujiqiyuan** [comment]
wooway1991@gmail.com

**Comment by Ru12345678** [comment]
1104251716@qq.com

**Comment by jsj0622** [comment]
3467487813@qq.com

**Comment by whp2220** [comment]
whp2220@gmail.com

**Comment by huakaikanzhe** [comment]
shuaishuangfeng@163.com

**Comment by a2272000716** [comment]
建议添加下，订阅时做重复地址判断，因为很多重写每次都要自己添加，一大堆都是一个地址，标签也可以设置下自动识别，重复地址

**Comment by zhilun2021** [comment]
136216200@qq.com

**Comment by 2300199706** [comment]
23001999@mymbhd.wecom.work

**Comment by nspgh** [comment]
1101927915@qq.com

**Comment by Ru12345678** [comment]
1104251716@qq.com

**Comment by 2300199706** [comment]
***@***.***



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nspgh ***@***.***&gt;
发送时间: 2022年5月12日 14:53
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: 2300199706 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 
***@***.***

**Comment by 2300199706** [comment]
***@***.***

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ru12345678 ***@***.***&gt;
发送时间: 2022年5月12日 14:58
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: 2300199706 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 
***@***.***

**Comment by Mcletty** [comment]
1327572041@qq.com

**Comment by richchii1** [comment]
richardlee8663@gmail.com

**Comment by jaylsq** [comment]
1659325349@qq.com

**Comment by Contrass** [comment]
a269987232@gmail.com

**Comment by Ru12345678** [comment]
Issue#21


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: huakaikanzhe ***@***.***&gt;
发送时间: 2022年5月12日 14:59
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: Ru12345678 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 ***@***.*** 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: nspgh ***@***.***&amp;gt; 
 发送时间: 2022年5月12日 14:53 
 收件人: Kimentanm/aptv ***@***.***&amp;gt; 
 抄送: 2300199706 ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21) 
 
 
 
 
 
   
 ***@***.***

**Comment by Contrass** [comment]
已收到邮件。

**Comment by zx875** [comment]
26846986@qq.com

**Comment by Crush-7S** [comment]
798510200@qq.com

**Comment by cnm2021** [comment]
xingjia0479626@163.com

**Comment by Mcletty** [comment]
liudingkun405@gmail.com

**Comment by cl514** [comment]
4147444@Gmail.com

**Comment by jaylsq** [comment]
lxq85816@163.com

**Comment by cnm2021** [comment]
yjl8021@gmail.com

**Comment by Moliiii** [comment]
466687162@qq.com

**Comment by hongjlgd** [comment]
2372678797@qq.com

**Comment by nb100** [comment]
1667473719@qq.com

**Comment by jaylsq** [comment]
lxq85816@163.com

**Comment by jack-e5** [comment]
200636521@qq.com

**Comment by dishao123** [comment]
jiajiunwork@gmail.com

**Comment by sujianlang** [comment]
785606706@qq.com

**Comment by smiledd** [comment]
903579182@qq.com

**Comment by huang003** [comment]
1449633053@qq.com

**Comment by smiledd** [comment]
***@***.***





------------------ 原始邮件 ------------------
发件人: huang003 ***@***.***&gt;
发送时间: 2022年5月12日 16:42
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: smiledd ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 
***@***.***

**Comment by Ru12345678** [comment]
2499327998@qq.com

**Comment by 7375747376** [comment]
737574376@qq.com

**Comment by laoyu1120** [comment]
laoyu1120@gmail.com

**Comment by kk1550719583** [comment]
1550719583@qq.com

**Comment by smiledd** [comment]
#21





------------------ 原始邮件 ------------------
发件人: kk1550719583 ***@***.***&gt;
发送时间: 2022年5月12日 16:59
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: smiledd ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 
***@***.***

**Comment by smiledd** [comment]
Issue #21&nbsp;





------------------ 原始邮件 ------------------
发件人: kk1550719583 ***@***.***&gt;
发送时间: 2022年5月12日 17:04
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: smiledd ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)

**Comment by kk1550719583** [comment]
&nbsp;(Issue #21)
&amp;mdash;
Reply to this email directly

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: smiledd ***@***.***&gt;
发送时间: 2022年5月12日 17:05
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: kk1550719583 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)

**Comment by Coy2020** [comment]
956114758@qq.com

**Comment by zhanglei4606** [comment]
zhang460653354@gmail.com

**Comment by kk1550719583** [comment]
Issue #21

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: smiledd ***@***.***&gt;
发送时间: 2022年5月12日 17:03
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: kk1550719583 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 #21 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: kk1550719583 ***@***.***&amp;gt; 
 发送时间: 2022年5月12日 16:59 
 收件人: Kimentanm/aptv ***@***.***&amp;gt; 
 抄送: smiledd ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21) 
 
 
 
 
 
   
 ***@***.***

**Comment by Coy2020** [comment]
***@***.***



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kk1550719583 ***@***.***&gt;
发送时间: 2022年5月12日 17:09
收件人: Kimentanm/aptv ***@***.***&gt;
抄送: Coy2020 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)





 Issue #21 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: smiledd ***@***.***&amp;gt; 
 发送时间: 2022年5月12日 17:03 
 收件人: Kimentanm/aptv ***@***.***&amp;gt; 
 抄送: kk1550719583 ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21) 
 
 
 
 
 
  #21  
   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: kk1550719583 ***@***.***&amp;amp;gt;  
  发送时间: 2022年5月12日 16:59  
  收件人: Kimentanm/aptv ***@***.***&amp;amp;gt;  
  抄送: smiledd ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;  
  主题: Re: [Kimentanm/aptv] TF内测组邀请，名额有限，请在下方回复邮箱 (Issue #21)  
   
   
   
   
   
     
  ***@***.***

**Comment by zhanglei4606** [comment]
kk1550719583 ***@***.***>于2022年5月12日 周四17:10写道：

**Comment by zhanglei4606** [comment]
张朝磊 ***@***.***>于2022年5月12日 周四17:11写道：

**Comment by zhanglei4606** [comment]
张朝磊 ***@***.***>于2022年5月12日 周四17:15写道：

**Comment by Kimentanm** [comment]
测试组已满，下次开放请等待通知~

**Comment by zhanglei4606** [comment]
zhang460653354@gmail.com

**Comment by donghaiz99** [comment]
903107220@qq.com
