### ISSUE TITLE
河北联通组播放不了

### ISSUE THREAD

**Issue by sunzhe1234** [Kimentanm/aptv#24]
istb,影音宝,filebox都能播

**Comment by sunzhe1234** [comment]
![Uploading 0355BC26-AA4A-4C7C-B0BF-955F97D07D68.png…]()

**Comment by Kimentanm** [comment]
暂时还不能播，后续会支持的

**Comment by Kimentanm** [comment]
请尝试更新最新版本，然后使用VLC播放器测试版试一下

**Comment by Kimentanm** [comment]
已可播放，请在AppStore搜索APTV
