### ISSUE TITLE
建议增加单列紧凑模式

### ISSUE THREAD

**Issue by deanhzed** [Kimentanm/aptv#3]

**Comment by Kimentanm** [comment]
确实是有这个feature在开发列表里，不过可能会推迟一段时间更新，现阶段的任务开发AppleTV端

**Comment by deanhzed** [comment]
有些低清晰度源全屏播放无法保持16:9，建议添加强制比例选项

**Comment by Kimentanm** [comment]
> 有些低清晰度源全屏播放无法保持16:9，建议添加强制比例选项

收到，已记录到开发列表，感谢反馈

**Comment by Kimentanm** [comment]
均已实现
