### ISSUE TITLE
通过gitee仓库配置的源无法解析

### ISSUE THREAD

**Issue by zhxs555** [Kimentanm/aptv#30]
通过gitee仓库配置的源无法解析，但通过本地导入的没问题，同一地址其他直播源软件可以正常解析

**Comment by zhxs555** [comment]
这个测试
https://gitee.com/aszx001/sdiptv/raw/master/test.m3u

**Comment by Kimentanm** [comment]
链接无法访问，请检查gitee的配置，后者直接使用github托管文件
<img width="421" alt="image" src="https://user-images.githubusercontent.com/25970284/184893193-3dcb9531-0e08-4dfa-b86c-f654c8d4d4d0.png">
