### ISSUE TITLE
tvos版本几个建议，大佬看看~ o(*￣▽￣*)ブ

### ISSUE THREAD

**Issue by nuoooo** [Kimentanm/aptv#32]
1、打开默认是收藏页
2、也可以自选图标
3、能否像infuse样，开机首页带预览

**Comment by Kimentanm** [comment]
您好，您提的三项建议，除了第二项tvOS没有提供相应的api无法实现外，其他两项都在待开发列表中，请等待后续的版本更新~

**Comment by nuoooo** [comment]
> 您好，您提的三项建议，除了第二项tvOS没有提供相应的api无法实现外，其他两项都在待开发列表中，请等待后续的版本更新~

或者默认图标换成IOS默认那个呢，感觉那个好看点

**Comment by halolake** [comment]
> > 您好，您提的三项建议，除了第二项tvOS没有提供相应的api无法实现外，其他两项都在待开发列表中，请等待后续的版本更新~
> 
> 或者默认图标换成IOS默认那个呢，感觉那个好看点

我也是因为tvOS的图标，一直没有下决心换APTV。

**Comment by Kimentanm** [comment]
第一项已经完成了
第二项已经找到相关Api正在开发中

**Comment by zjfeiye** [comment]
> > > 您好，您提的三项建议，除了第二项tvOS没有提供相应的api无法实现外，其他两项都在待开发列表中，请等待后续的版本更新~
> > 
> > 
> > 或者默认图标换成IOS默认那个呢，感觉那个好看点
> 
> 我也是因为tvOS的图标，一直没有下决心换APTV。

怎么着也比istb好看多了😅

**Comment by Kimentanm** [comment]
第三项已完成

**Comment by Kimentanm** [comment]
tvOS更换图标功能已实现，不就会更新到AppStore
![Simulator Screen Shot - Apple TV 4K (3rd generation) - 2023-03-06 at 18 03 05](https://user-images.githubusercontent.com/25970284/223080233-8f8a729c-278c-4fff-9497-9b7ffde11801.png)
