### ISSUE TITLE
ios16 测试版上有问题吗？

### ISSUE THREAD

**Issue by czkoko** [Kimentanm/aptv#33]
在最新ios16测试版上问题好像挺严重的，iphone11和ipad mini 5都一样情况。
1.切换频道无法关闭上个频道的声音，好多个频道的声音同时在播放。
2.很难切换到全屏模式。
3.播放时左右滑动切换频道会卡住。
4.每个频道都会重新加载一次epg列表，并且加载过程中画面会卡住几秒。

反倒是tvos 16上几乎完美，偶尔有闪退，总体来说应该是apple tv目前使用体验最好的了，解码速度相当快。

**Comment by Kimentanm** [comment]
是的，今天iOS16刚发布了RC版本，之前都是Beta，我要准备开始适配iOS16了
等iOS16正式版一发布，我也就跟着一起发布

**Comment by Kimentanm** [comment]
1.0.6已适配iOS16，请在AppStore中更新应用
