### ISSUE TITLE
When will CarPlay be supported?

### ISSUE THREAD

**Issue by Jackzhjam** [Kimentanm/aptv#36]
Do you have any specific plans?When will it be updated by software?How is the current price of Pro version in 18 yuan, not 12 yuan?

**Comment by Kimentanm** [comment]
CarPlay相关申请已经发给Apple了，但是还没有得到回复
初始价格是12元，tvOS端上架后，涨价到18元了

**Comment by Jackzhjam** [comment]
I understand the CarPlay problem. Personally, I suggest that the paid Pro version should be distinguished. I can't use the Mac and Tv versions. Can the mobile phone version be cheaper? I can transfer money to you directly.

**Comment by Jackzhjam** [comment]
我可以把Apple Id邮箱号给你，然后你帮我开通，我用支付宝付款给你，只要手机版本的，能不能便宜点？
