### ISSUE TITLE
说两个建议

### ISSUE THREAD

**Issue by Yonsm** [Kimentanm/aptv#39]
良心app、精心app，先点赞！一见如故，直接买了（虽然Pro里的功能我其实也不需要）

说两个建议：

1. 支持rtsp（现在看 APTV 似乎仅支持 udpxy 导出的 http，很多IPTV可以rtsp直接分流访问的）；
2. EPG匹配的时候支持 title（而不仅是 tvg-name 或  tvg-id），否则目前这样会造成大量 title 和 tvg-name 字段重复
`#EXTINF:022, group-title="卫视" tvg-name="江苏卫视", 江苏卫视`

更长远地YY，如果能把IPTV怎么搭建、分享等搞出来，集大成了

**Comment by Kimentanm** [comment]
1.支持 rtsp
2. 支持使用title匹配EPG
你说的这俩目前都是支持的，你再试试

**Comment by Yonsm** [comment]
1. 我没实测，上海联通的朋友说APTV不支持这个：https://github.com/Yonsm/IPTV/blob/master/shanghai/unicom.m3u8（KODI和INNA支持）
2. title 是指逗号后面的，比如下面这个，是看不到江苏卫视的EPG的：
#EXTINF:022, group-title="卫视", `江苏卫视`

**Comment by Yonsm** [comment]
rtsp再次确认了一下，可以支持了。但据说起播有点卡（后面不卡）。切换系统播放器依然。自己写的android app和inna都不卡
