### ISSUE TITLE
无法匹配帧率

### ISSUE THREAD

**Issue by my5123** [Kimentanm/aptv#40]
对于不同帧率的视频，无法动态调整为对应帧率，完成画面卡顿，apple tv已经开了匹配帧率。

另，这个问题油管有、aptv有、cheer有，目前用下来只有infuse匹配没问题。

目前只能看25、50p的源时，apple tv设为50hz，看30、60p源再改为60hz。

**Comment by haoyu1999** [comment]
@Kimentanm 作者你好，请问这个问题有什么进展吗？
当显示刷新率与源的帧率不匹配时，画面会出现卡顿。手动调节很不方便，这个功能是迫切需要的。

**Comment by my5123** [comment]
> @Kimentanm 作者你好，请问这个问题有什么进展吗？ 当显示刷新率与源的帧率不匹配时，画面会出现卡顿。手动调节很不方便，这个功能是迫切需要的。

仍未解决

**Comment by Kimentanm** [comment]
暂时无法解决

**Comment by my5123** [comment]
> 暂时无法解决

方便科普下原因吗

**Comment by Kimentanm** [comment]
tvOS的1.1.4版本更新了匹配帧速率的功能
需要在设置-高级设置-实验室中开启
