### ISSUE TITLE
这个app太棒了，不过能否在播放界面直接选台？

### ISSUE THREAD

**Issue by zjfeiye** [Kimentanm/aptv#41]
早知道不给istb送钱了，支持支持，果断付费了，我主要用appletv版本，似乎没发现在播放界面直接选台的功能，希望能加上
另外，刚开始用的时候按播放/暂停键怎么都出不来菜单，一度以为这个功能没开发完成，后来不知道怎么搞了一下好了

**Comment by Kimentanm** [comment]
电视端，从左向右滑动遥控器，或者长按左键就有选台的侧边栏了
![image](https://user-images.githubusercontent.com/25970284/206367383-e5655edc-36c8-4a0e-9f1b-64d7d4f8308e.png)

**Comment by zjfeiye** [comment]
> 电视端，从左向右滑动遥控器，或者长按左键就有选台的侧边栏了 ![image](https://user-images.githubusercontent.com/25970284/206367383-e5655edc-36c8-4a0e-9f1b-64d7d4f8308e.png)

了解，回去试试
