### ISSUE TITLE
appletv端切台的时候偶尔闪退

### ISSUE THREAD

**Issue by zjfeiye** [Kimentanm/aptv#42]
appletv端切台的时候偶尔闪退，但是我没找到规律，很抱歉没法提供更多反馈

**Comment by Kimentanm** [comment]
是频道页带预览图的切台，还是播放时的侧边栏切台呢？

**Comment by zjfeiye** [comment]
> 是频道页带预览图的切台，还是播放时的侧边栏切台呢？

播放时侧边栏切台闪退

**Comment by Kimentanm** [comment]
请问是否用的是带有很多4K频道的配置？

**Comment by zjfeiye** [comment]
> 请问是否用的是带有很多4K频道的配置？

某宝上“大猫金牌服务安装”家买的源，共540个频道，4K频道10个

**Comment by Kimentanm** [comment]
好的，明白了，我这边看一下错误日志
