### ISSUE TITLE
关于 APTV 的几个建议

### ISSUE THREAD

**Issue by iCodyYang** [Kimentanm/aptv#44]
已付费购买，很喜欢，目前已作为主力app使用，感谢作者
使用过程中发现了一些可以优化的地方，希望作者可以考虑下

### iOS 端
1. 希望「收藏」栏内，进入播放页面后，「频道」列表可以显示其他台
2. 同样的源，在 tvos 播放不卡，ios有时候会卡或者闪退

### tvOS 端
1. 取消换台黑屏的设置，改为停留在上一台最后一帧，黑屏比较晃眼。如担心当卡的时候无法确认是那个台卡了，可以把这个功能做成一个开关。
2. 打开app 默认直接播放默认列表或者收藏列表
3. 优化换台UI，目前只出现台的名字略微有些简陋，可参考 tv+
4. TF版本可以优先考虑付费用户

以上建议按个人优先级排序，再次感谢作者

**Comment by Kimentanm** [comment]
您好，感谢您的建议
iOS
1. 收藏的播放页面还在优化中
2. 这个很难确定是什么原因

tvOS
1. tf中已添加换台时是否黑屏的选项
2. 在设置中可以设置首选标签
3. 这个功能在计划中会稳步开发，页面UI不会参考任何App，会有APTV自己的风格
4. TF名额有限，会不定期开放，可以加入tg群或者qq群蹲开放的通知

**Comment by iCodyYang** [comment]
感谢回复

### iOS
2. 这个出现的不频繁，下次出现的时候我再反馈

### tvOS
2. 我可能没有表达清楚，是希望打开app，直接播放
3. 点赞
4. 一直在，没蹲到 哈哈
