### ISSUE TITLE
希望能够支持空间音频～

### ISSUE THREAD

**Issue by boybook** [Kimentanm/aptv#45]
KSPlayer播放器似乎已经支持了空间音频
https://github.com/kingslay/KSPlayer/issues/330

但是使用APTV的Mac和iOS客户端时，播放杜比全景声5.1电视直播时，依然无法启用全景声模式；播放立体声节目时，也无法启用空间化立体声模式

希望大佬能够适配一下啦～

**Comment by Kimentanm** [comment]
目前测试版已经更新到KSPlayer的最新版，5.1声道和7.1声道目前测试已经没有问题
空间音频还没有测试
Mac端的测试版刚更新了一个版本，你可以测试一下5.1声道
