### ISSUE TITLE
MEMC 运动补偿的问题

### ISSUE THREAD

**Issue by czkoko** [Kimentanm/aptv#46]
你好，aptv 是否可以实现运动补偿功能，我的电视是支持 memc 运动补偿功能的，
理论上运动补偿是电视机芯片处理的，和信号源无关，
我用iplaytv和infuse播放25p的节目都是很丝滑的，和50p一样效果，
但aptv播放同一个25p的节目就明显没有补帧，不知道问题出在哪里

**Comment by Kimentanm** [comment]
这不是动态补偿的问题，这是动态帧率的问题
#40 和这个是同一个问题，暂时无法解决
