### ISSUE TITLE
節目單時差

### ISSUE THREAD

**Issue by PoorerImmune** [Kimentanm/aptv#47]
我的直播源裡有國外的電視頻道，這些頻道的 EPG 存在時區不同步的問題。由於我並未採用 App 內建的 XML 位址，第三方的 XML 格式的節目單又是從 UTC+0 開始計時，導致我的節目單的播出時間與電視台正在播出的節目相差了 8 個小時。你的 App 能否提供時區偏移的選項，或者支援 m3u8 檔案中的 tvg-shift 屬性？

**Comment by mingweiarthurli** [comment]
作者你好，我人在海外观看国内频道时也遇到了这个问题，EPG节目单使用的是app自带的，节目单内容是对的，但是观看内地节目时，当前播放节目与节目单上列出的节目不对应，观察了下，节目单是国内时区的，但是显示当前播放的节目是按照本地时区来的，这同时也导致了节目回放失败。
希望作者能尽快修复这个问题，谢谢！

**Comment by Never2333** [comment]
作者你好，目前在最新版本中仍出现EPG节目单不会随用户当前时区自动更改的问题，只会按照当地时区进行显示。望修复，谢谢！

**Comment by dzing007** [comment]
我是DZ，已收到您的邮件。

**Comment by SlimTime** [comment]
作者您好，我目前也是碰到一樣的問題，我使用的節目表是對的，但是會抓到錯誤的時區，希望能夠調整時區的顯示，謝謝!

**Comment by Kimentanm** [comment]
是否可以给我提供一个测试使用的节目表地址

> 作者您好，我目前也是碰到一樣的問題，我使用的節目表是對的，但是會抓到錯誤的時區，希望能夠調整時區的顯示，謝謝!

**Comment by smile912001** [comment]
我也有一樣的問題
提供測試節目表地址
https://epg.pw/xmltv/epg_TW.xml
