### ISSUE TITLE
直播源更新後無法立即反映在 App 中

### ISSUE THREAD

**Issue by PoorerImmune** [Kimentanm/aptv#50]
一旦在遠端維護的直播源有更新，使用者更新訂閱後，變更無法立即顯示於 App 中，必須退出 App 後重開。另外，你的 App 在更新直播源後無法自動清除先前的快取檔。經常出現的一種情況是，我在遠端換了 tvg-logo 的指向連結，但是原來的舊台標還在頻道旁邊，並沒有更新。

**Comment by Kimentanm** [comment]
已经修复了，将在下个版本中更新
