### ISSUE TITLE
apptv切换台卡顿

### ISSUE THREAD

**Issue by richard-woo** [Kimentanm/aptv#55]
我使用的是最新版的Appletv 2022，A15处理器那款，系统版本是tvOS16.4

目前我使用的是远程的一个IPV6直播源（直播源网址我放在下面），每次回来打开aptv，基本上是每次都会出现卡顿，操作步骤如下：
1.打开aptv app
2.选择已经添加的远程ipv6直播源
3.按遥控器向下建换台
4.每个台看2-3秒就换，也就是典型的换台场景
5.基本上每次都会出现换到第4或5个台，有时候换第二个台就会卡住，播放停止没有声音。长时间无法恢复播放，一直在转圈。

出现如果继续换台，下一个台正常播放，再换回来，刚才卡住的台也正常播放了。

已经用其他app交叉验证过不是播放源的问题。

希望您能看看这个bug，如果需要我提供信息，我会很乐意提供。
直播源网址：https://live.fanmingming.com/tv/m3u/ipv6.m3u

**Comment by Kimentanm** [comment]
收到反馈的问题了，我今天就来按照步骤尝试复现一下你说的问题
若有进展我会继续回复该issue

**Comment by Kimentanm** [comment]
该bug已修复，已更新到Testflight测试版，这两天就会更新到AppStore
