### ISSUE TITLE
关于m3u

### ISSUE THREAD

**Issue by DoLNw** [Kimentanm/aptv#56]
可否请教一下，如何获取某一个房间号虎牙的直播源？
还有，如果获取的是flv的连接，APTV能播放吗？

**Comment by Kimentanm** [comment]
首先，flv链接可以直播播放，使用空白配置就可以添加单个的flv链接
这里是空白配置的教程：https://docs.aptvapp.com/config/kong-bai-pei-zhi
其次，这个是虎牙频道的示例链接：http://live.aptvapp.com/live/huya/11342412
后面的数字是房间号，修改房间号即可，同样是使用空白配置添加
