### ISSUE TITLE
首次使用后遇到的一些问题

### ISSUE THREAD

**Issue by kery** [Kimentanm/aptv#57]
刚知道这个App，好用，购买了Pro版本，不过遇到些问题。

## 第一，一个频道只能一个分组
KODI和ntPlayer是可以支持一个频道多个分组的，分组由分号隔开就行，如：group-title="卫视;本地"

## ~~第二，频道超过一屏后，最底下一行显示不全，频道信息被底部Tab给遮挡了~~
重装App后问题已消失

## 第三，每次添加源后App就崩溃
崩溃后，须再次打开App手动刷新源，而且点击顶部的刷新按钮没用，要点击源那一栏才行。

## 第四，“正在播放”不能自动更新
当前在看的节目A结束后，“正在播放”不能自动更新为下一节目，切换频道再切换回来也不行，必须退出播放，再次进入。

**Comment by Kimentanm** [comment]
1. 目前没有做多分组功能
2. 左滑配置点三个点可以出来编辑配置的选项
3. 请问添加的是订阅配置还是本地配置，如果可以的话请把相应的资源发送给我
4. 确实有该问题，已收到

**Comment by kery** [comment]
1. 能否支持多分组功能呢？逻辑上来说一个频道是可以属于多个分组的；
2. 是的，之前试出来了，所以Issue已经修改；
3. 订阅配置。用你的示例源（https://pastebin.com/raw/40MQLfcA）就行。重现前需要先删除已经添加的所有源。手机信息：iPhone12 (iOS 16.5)

**Comment by Kimentanm** [comment]
信息不全你可以重新安装app看看，重装之后，你再试试 这个链接 https://pastebin.com/raw/40MQLfcA 会不会崩溃，因为我测试了很多次都没有问题

会支持多分组功能，此功能在开发计划中

**Comment by kery** [comment]
重装了，也会崩溃，每次必现。你重现时清空现有的源没？

**Comment by Kimentanm** [comment]
有的，清空了，依然是没有崩溃
这样，如果可以的话麻烦提供一个邮箱给我，我发你一个tf版，如果还是会闪退请提交一下错误日志，方便我排查问题，谢谢~

**Comment by kery** [comment]
可以，发我主页的邮箱吧。

**Comment by Kimentanm** [comment]
已发送邀请，若使用过程中崩溃请在输入框中输入名字或者其他信息，方便我可以快速定位

**Comment by kery** [comment]
没收到，邮箱地址是不是少输了个点？

**Comment by Kimentanm** [comment]
邮箱地址无误，重发邀请了，你再看看邮件，特别是垃圾邮箱

**Comment by kery** [comment]
没在垃圾箱，直接在给删除了。已重现，崩溃信息已提交。

**Comment by Kimentanm** [comment]
感谢反馈，问题已修复，将尽快更新

**Comment by Kimentanm** [comment]
最新的TF中已更新支持多分组功能
