### ISSUE TITLE
EPG时长显示错误

### ISSUE THREAD

**Issue by kery** [Kimentanm/aptv#58]
EPG如下，《非遗里的中国》时间是2023-06-25 23:57:00 ~ 2023-06-26 00:00:00
```xml
    <programme start="20230625223400 +0800" stop="20230625235700 +0800" channel="3954">
        <title lang="zh">星光大道</title>
    </programme>
    <programme start="20230625235700 +0800" stop="20230626000000 +0800" channel="3954">
        <title lang="zh">非遗里的中国（8）</title>
    </programme>
```

但是App显示的时长是"-23小时-57分钟"
<img width="560" alt="Snipaste_2023-06-25_14-44-44" src="https://github.com/Kimentanm/aptv/assets/3469040/0d90e9ca-8a2e-4f2a-984c-67fdd5a1e34b">

**Comment by Kimentanm** [comment]
请问用的是哪个EPG源？

**Comment by kery** [comment]
从运营商那获取的，但可能是他们系统bug的原因，stop在start之前。具体来说就是start是20230625235700，stop是20230625000000 （同一天的凌晨），这样导致Kodi显示不了这条节目单信息。而且这也不符合其他EPG条目的规则，即一个EPG条目的stop时间是下一条EPG条目的开始时间。

为了解决Kodi显示不了这种EPG条目的问题，我自动给纠正成了26日凌晨。

**Comment by Kimentanm** [comment]
按我的理解，start是20230625235700，stop是20230625000000是会出现上面图片的情况的，你修改成26日凌晨如果还是上面的情况，你可以去缓存中删除这一个epg的缓存，然后重新打开App，会重新download epg

**Comment by kery** [comment]
不是的，我的EPG源从我购买这个App之前就已经纠正成26日了，所以和缓存没关系。而且我今天下载你给的测试版本后，重新添加了源，现在看这个问题也在。

**Comment by Kimentanm** [comment]
感谢反馈，已修复这个问题，将在下个版本中更新
<img width="496" alt="image" src="https://github.com/Kimentanm/aptv/assets/25970284/4b3092c2-0ba5-43f4-b7dc-9dfb22e1ee8b">
