### ISSUE TITLE
删除EPG缓存后，新加载EPG和文件内容对不上，且APP上显示EPG也有问题

### ISSUE THREAD

**Issue by kery** [Kimentanm/aptv#60]
删除缓存重新加载EPG后发现两个问题。

一、APP里显示正在播放6月27日的《熟年（36）》，这没问题，但是后面28日的节目单却显示的是“已播放”；
<img width="444" alt="Snipaste_2023-06-27_22-12-12" src="https://github.com/Kimentanm/aptv/assets/3469040/a718fac7-d62d-49c4-8113-bd45fcfc9dba">
<img width="442" alt="Snipaste_2023-06-27_22-15-10" src="https://github.com/Kimentanm/aptv/assets/3469040/dd0afcb4-b54e-45b0-9d0a-0f69ae3e70f7">

二、28日的节目单内容和27日的一样（EPG文件里没问题）。EPG原文件已上传，见文章末尾。

这是27日末尾的内容
```xml
    <programme start="20230627220000 +0800" stop="20230627223400 +0800" channel="3954">
        <title lang="zh">晚间新闻</title>
    </programme>
    <programme start="20230627223400 +0800" stop="20230628000000 +0800" channel="3954">
        <title lang="zh">典籍里的中国Ⅱ（3）</title>
    </programme>
    <programme start="20230628000000 +0800" stop="20230628000600 +0800" channel="3954">
        <title lang="zh">典籍里的中国Ⅱ（3）</title>
    </programme>
```

这是28日末尾的内容
```xml
    <programme start="20230628210100 +0800" stop="20230628220000 +0800" channel="3954">
        <title lang="zh">熟年（38）</title>
    </programme>
    <programme start="20230628220000 +0800" stop="20230628223400 +0800" channel="3954">
        <title lang="zh">晚间新闻</title>
    </programme>
    <programme start="20230628223400 +0800" stop="20230629000000 +0800" channel="3954">
        <title lang="zh">典籍里的中国Ⅱ（4）</title>
    </programme>
```

从上面的图片可以看到，28日的EPG内容显示有问题。

EPG原文件在此：[epg_formatted.zip](https://github.com/Kimentanm/aptv/files/11883279/epg_formatted.zip)

**Comment by Kimentanm** [comment]
已知问题，已经修复了，还未发布版本

**Comment by Kimentanm** [comment]
新的测试版通过审核已发布

**Comment by kery** [comment]
嗯，测了下，没问题了。但是有个其他的小问题，我的epg只提供了两天的历史数据，即26日及以后的，App会显示更早的数据，且显示为“精彩节目”。
![IMG_1655](https://github.com/Kimentanm/aptv/assets/3469040/00f3840a-1645-4772-9a44-e8213f03493c)

**Comment by Kimentanm** [comment]
这个其实是为了回看，在没有节目单的情况下也可以做到七天回看，只不过回看区间比较大

**Comment by kery** [comment]
能否优化下呢？如果提供了EPG的话，优先以EPG的信息为准？

**Comment by Kimentanm** [comment]
只是看上去会有点奇怪，但是不往上翻一般也看不见，而且确实有很多人有这样的回看需求，所以不会作为优化项

**Comment by kery** [comment]
好的。
