### ISSUE TITLE
关于开机播放的问题

### ISSUE THREAD

**Issue by dawuman** [Kimentanm/aptv#62]
平台：APPLE TV 4K 2022版 TVOS17
APTV版本：1.1.0
已购入专业版，使用效果很好，但是用了一段时间发现有个问题。先说下背景，因为平时要上班，家里老人白天用APTV看电视，希望操作简单方便。因为我是购买了一个收费源，里面有很多分类，几百个台，但是因为我是移动光纤，只有其中一个分类（魔百ipv6）比较稳定，画质好。其它要么看不了，要么画质差，内容重复，所以我一般都是固定选择这个分类，只看里面的几十个台。

现在使用中遇到的具体问题如下：
在设置中将启动时播放打开，默认播放来源设置为最近播放，结果下次运行APP时，频道就变成只有最近播放的20个频道了，如果想看其它台，只能操作返回到魔百ipv6分类下才可以。

期望的效果：
比如我是在选中魔百ipv6分类下的CCTV6播放中关机的，那么下次我打开APTV时，应该自动播放这个频道，而且按频道+-是切换魔百ipv6分类下的CCTV6的前一个频道或后一个频道。或者是打开APTV时，自动播放魔百ipv6分类下的第一个频道，而不是全部频道的第一个频道。还有就是在第一个频道播放时，切换上一个频道好象是无效的，应该做成象有线电视那样，可以循环切换，在最后一个频道换下一个台，自动切到第一个频道，在第一个频道按上一个台，自动切到最后一个频道。

另外我还发现一个问题，假如将默认播放来源设置为当前配置，启动时自动播放第一个频道，在我这里是CCTV13，这个时候按频道+-是没有用的，切来切去都是这个频道，只能滑动调出侧边菜单，才可以正常换台。

以上，谢谢，如果是我哪里设置不对，也请指出。

**Comment by dawuman** [comment]
这其实是另一个需求：【记住当前配置上一次播放的频道】

你这个当前配置是指什么，按照我的理解，我有一个订阅，下面有ABCD四个分类，我关机前是在看C分类下的某一个频道，那么我的当前配置应该是C分类，而不是整个订阅，但实际现在是整个订阅。

**Comment by dawuman** [comment]
因为我现在在APP中设置播放来源为当前配置时，再开机时它并不是播放C分类下的第一个频道，而是订阅中全部分类的第一个频道。

**Comment by Kimentanm** [comment]
是的，默认就是从整个配置的第一个频道开始播放的
这就解释了为什么没有办法按频道+-换台了，因为选了分类的话只会在分类下换台，但是当前播放的频道又不在选择的分类下，所以没有办法+-换台
我会优先【记住当前配置上一次播放的频道】这个功能

**Comment by dawuman** [comment]
【记住当前配置上一次播放的频道】这个功能，我理解为实现以后，我就可以达到我想要的效果，如果我一直选择C分类，并在这下面换台看，那么只要我不去选择别的分类，那么以后开机就只会在C分类下来回换台

**Comment by Kimentanm** [comment]
是的，就是你理解的这个意思

**Comment by dawuman** [comment]
其实这样只解决了我的问题，更优雅的方式应该是可以选默认播放来源为我的收藏，这样就可以把不同分类的好频道集合在一起，想看就看。假如收藏的频道没有了，可以做个提示，此频道源已不存在，是否暂时屏蔽。
还有就是那个订阅源应该可以设置一天自动更新一次吧，现在只能手动更新。

**Comment by Kimentanm** [comment]
默认播放来源改为我的收藏，这个功能已经做好了，只不过上了测试版还没上商店版
订阅源可以设置自动刷新，默认为8小时更新一次

**Comment by dawuman** [comment]
大佬你在的话，我就一气说完吧，还有一个建议，不知道合不合理，就是apple tv的遥控器不是容易误触吗，可否在设置里加一个专注模式的开关，这个时候只能换台，静音或是调出侧边栏，返回键必须长按才起作用。老人在家看电视一点错了就给我打电话，呵呵，麻烦。

**Comment by Kimentanm** [comment]
已解决开机播放相关问题
