### ISSUE TITLE
appletv版不支持回看

### ISSUE THREAD

**Issue by luckymrwang** [Kimentanm/aptv#66]
相同的源，iPhone上能支持回看，但是appletv不支持(最新版本)，怎么修复啊？

**Comment by Kimentanm** [comment]
你说的不支持回看，是看不到节目单，还是有节目单但是点进去不能回看
我猜是前者

**Comment by luckymrwang** [comment]
你好，是后者，能看到节目单，但是点进去不能回看，就是点了没反应

**Comment by luckymrwang** [comment]
> 你说的不支持回看，是看不到节目单，还是有节目单但是点进去不能回看 我猜是前者

你好，是后者，能看到节目单，但是点进去不能回看，就是点了没反应

**Comment by Kimentanm** [comment]
如果可以的话，能提供一下你正在回看的直播源吗？

**Comment by luckymrwang** [comment]
> 如果可以的话，能提供一下你正在回看的直播源吗？

用的这个开源的：[live](https://github.com/fanmingming/live)

https://live.fanmingming.com/tv/m3u/global.m3u

EPG地址用的APTV APP默认地址

**Comment by Kimentanm** [comment]
这个源的回看格式属于自定义回看，iOS也是刚支持的，tvOS要下个版本才支持

**Comment by luckymrwang** [comment]
> 这个源的回看格式属于自定义回看，iOS也是刚支持的，tvOS要下个版本才支持

好的，感谢
