### ISSUE TITLE
mac版本双击频道会打开两个窗口

### ISSUE THREAD

**Issue by 0x5e** [Kimentanm/aptv#67]
感谢 @Kimentanm ，app很好用：）
反馈个小问题，正常来说应该没有一个频道开多个窗口的需求吧，如果频道点太快就会打开两个窗口叠在一起，不仔细看还不容易发现。

**Comment by Kimentanm** [comment]
对，目前没有屏蔽掉双击这个操作，后面我会把双击给屏蔽掉，就不会出现两个窗口了

**Comment by yangwudong** [comment]
这个应该比较好改吧？辛苦改一下，谢谢啦

**Comment by 0x5e** [comment]
这个其实是两次单击事件吧，可以加一个空的双击事件最省事

**Comment by Kimentanm** [comment]
已在macOS 1.3.0版本中优化了这个问题
