### ISSUE TITLE
tvOS端预览图问题

### ISSUE THREAD

**Issue by 0x5e** [Kimentanm/aptv#69]
偶现刷新预览图时，第一屏没有刷新（没有转菊花），但是下面的有在刷新。滚动到第二页（第一页完全不显示）之后再滚回去就触发刷新了。tableviewcell的重用问题？

另外，预览图的加载是否可以按照一定的优先顺序进行？这样对于某些频道比较多的列表体验可能会更好一点，目前比较容易出现第一屏才只加载出三四张图，下面好几屏的预览图已经出来了。

**Comment by Kimentanm** [comment]
我猜测你是遇到了这种情况：
1. 第一屏刷新预览图的时候由于tv的内存不足，app主动断掉了所有的加在预览图的线程，所以你看上去是没有刷新
2. 当你往下滑动的时候才会触发下面频道刷新，重新滚回去的时候会判断当前频道是否有预览图，如果没有就会继续加载刷新
3. 没有办法按照优先顺序进行，刷新预览图的过程是一个异步刷新的过程，优质的频道会更快刷新出来预览图，有一些频道可能质量不佳需要很长的刷新时间，如果按照顺序进行的话，那么势必需要将异步改为同步，这样会大大增加刷新预览图的时间
4. 频道比较多的列表也不会有问题，因为本身刷新预览图就是按照当前可视窗口来的，只要不往下滑动屏幕是不会去加载预览图的

**Comment by 0x5e** [comment]
感谢答复，确实我的频道第一屏的都是央视，可能是属于访问量比较高，图片加载比较慢的，末尾的一些小频道加载很快。
今天又尝试了几次好像没有复现出当时的情况，基本上是停留在哪个位置就刷新当前屏幕的图片，这样是ok的。

不过今天发现手动刷新+滚动的操作闪退率很高，10次能复现出9次。并发数量是否有做控制呢？会不会我当时是因为并发量过大+网络不好的时候，第一屏的请求大多都失败了所以就没图+没菊花了。
