### ISSUE TITLE
三个问题

### ISSUE THREAD

**Issue by RoyLi-Pvt** [Kimentanm/aptv#77]
- 台标似乎不支持Webp格式
- 能否在隐藏频道预览的时候将台标显示为预览图？或者提供一个实现此行为的选项？
- 能否提供更频繁的频道列表刷新选项？比如1分钟5分钟之类的
解释：我实现了一个自动抓取各种在线直播源并动态生成m3u的程序。它会自动刷新在线直播间所以需要比较频繁的更新，同时我的程序会自动获取预览图作为台标，部分直播源提供的预览图为webp格式，显示不出来

**Comment by RoyLi-Pvt** [comment]
额似乎现在的默认行为是会把LOGO显示在预览图位置的只是不会完全填充我一开始没看到是因为我自己的缩略图抓取过期了😄

**Comment by Kimentanm** [comment]
台不会完全填充
以后可能会提供刷新频率时间选择

**Comment by RoyLi-Pvt** [comment]
webp格式不兼容的问题和缩略图过期是独立的 使用webp格式的台标无论是否过期都无法显示

**Comment by Kimentanm** [comment]
webp格式我测试过了，可以正常显示，你可以使用下面这个图片做测试
https://img.whalenas.com:283/file/0.webp
