### ISSUE TITLE
tvOS 端所有频道均无法播放，iOS 端则没有问题

### ISSUE THREAD

**Issue by haoyu1999** [Kimentanm/aptv#79]
大佬，元宵节快乐！

我最近在 tvOS 端更新 APTV 后，所有频道都无法播放了。修改首选播放器、开关硬解码都无法解决。

相同的 m3u 文件在 iOS 端、相同 WiFi 网络下播放正常。在其他 tvOS IPTV 应用（BestTV）中播放也正常。

m3u 文件是本地上传的，直播源是内网 udpxy 服务器。

**Comment by Kimentanm** [comment]
您好，元宵节快乐！
首先，udpxy转发出来的单播是测试过没问题可以播放的，我这边建议可以卸载App重新安装试试
有的时候从低版本升级上来会导致一些问题

**Comment by haoyu1999** [comment]
已尝试卸载 App，然后从 App Store 重新安装，还是无法播放。

**Comment by Kimentanm** [comment]
我需要您提供更多的信息才可以辅助我确定问题，比如视频或图片
可以添加我的扣扣：956610177

**Comment by Kimentanm** [comment]
我需要您提供更多的信息才可以辅助我确定问题，比如视频或图片

**Comment by haoyu1999** [comment]
已通过尾号4133的QQ添加您

**Comment by Kimentanm** [comment]
没有收到好友请求呢，也可以通过手机App-设置-关于里面添加QQ群，这样也能联系到我

**Comment by haoyu1999** [comment]
上个月升级最新版本后已解决，谢谢
