### ISSUE TITLE
iOS端不能投屏到投影仪

### ISSUE THREAD

**Issue by yaoper** [Kimentanm/aptv#83]
23 年底的时候我记得在 iOS 端有投屏到我家的投影仪（xgimi极米）上看直播，后来就找不到投屏的按钮了。是这个功能下线了还是说投屏协议变化不被支持了？有计划支持或者支持更多协议的投屏功能么？

**Comment by Kimentanm** [comment]
目前只有AirPlay投屏功能，目前AirPlay只有在设置的首选播放器中选择系统播放器才可以激活
有计划支持DLNA投屏

**Comment by yaoper** [comment]
> 目前只有AirPlay投屏功能，目前AirPlay只有在设置的首选播放器中选择系统播放器才可以激活 有计划支持DLNA投屏

感谢～
