### ISSUE TITLE
播放器非常好，但有一个问题很影响使用

### ISSUE THREAD

**Issue by 5iphoto** [Kimentanm/aptv#87]
得益于cec功能，很多用户其实都是用一个电视遥控器来控制所有的设备，aptv的回看需要打开appletv遥控的触控功能向右滑动才能打开，导致了用别的遥控器根本无法使用回看功能，一旦需要回看就要切换遥控实在太割裂了。真诚的建议增加或者更换回看的触发方式，感谢🙏

**Comment by Kimentanm** [comment]
其他遥控器也可以使用长按【左方向键】唤出侧边栏
