### ISSUE TITLE
BUG: tvOS 18.0 播放界面回退直接进入桌面

### ISSUE THREAD

**Issue by bxb100** [Kimentanm/aptv#88]
目前是进入之后播放, 然后后退, 原本正常是回退到 `频道-全部` 界面的, 但是现在直接就回退到桌面了

如果设置了打开播放的话, 就无限循环了

**Comment by Kimentanm** [comment]
tvOS18目前还是早期beta版本，APTV的正在适配中

**Comment by bxb100** [comment]
理解

**Comment by Kimentanm** [comment]
已在APTV tvOS 1.2.6版本中修复，请更新App
