### ISSUE TITLE
滚动列表的性能卡顿，希望能够优化

### ISSUE THREAD

**Issue by DIPENG-XU** [Kimentanm/aptv#89]
- 当导入的视频源过多的时候，例如500个资源同时在列表中，上下滑动的时候会有明显的卡顿，包括在macOS、iOS和iPadOS上都有出现，tvOS我没有Apple TV所以没有相应的用户体验，希望能够修复一下这个问题。
- 技术补充说明，我了解过一点点的Android开发，Android开发中面对滚动页面，有一个RecyclerView可以复用部份item资源处理这个卡顿问题。iOS在技术细节上我不知道相对应的UI控件是什么，但是从技术大角度来讲可能是APTV在处理这个滚动页面的时候是不是没有复用item资源所以导致很卡？

**Comment by Kimentanm** [comment]
你指的500个资源是有500个频道吗
这个卡顿可能是来自于获取预览图这个过程，你可以在设置中关闭预览图的功能，然后再滑动列表试试看
