### ISSUE TITLE
接下来的主要任务是开发tv端版本，所以iOS App的新需求计划暂停开发

### ISSUE THREAD

**Issue by Kimentanm** [Kimentanm/aptv#9]
对于iOS版本的app大家有需求还是照样提issue，我也会正常记录，只是会延迟开发

**Comment by zss807532632** [comment]
感谢作者，期待tv端上线！

**Comment by wq369641177** [comment]
加油💪

**Comment by qaz793** [comment]
加油

**Comment by guozidi** [comment]
坐等tv

**Comment by whitexone** [comment]
支持一个

**Comment by Kimentanm** [comment]
APTV的tvos版本预计本周末可以上线测试预览版
![Screen Shot 2022-05-21 at 16 45 54](https://user-images.githubusercontent.com/25970284/169732595-dda6347f-492d-4241-8433-5dbe38a53955.png)

**Comment by Kimentanm** [comment]
APTV tvOS版本已上线Testflight，又需要参加测试的可以加tg群联系

**Comment by qaz793** [comment]
很想测试TVOS版，但是不知道如何加入



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月24日(星期五) 下午2:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kimentanm/aptv] 接下来的主要任务是开发tv端版本，所以iOS App的新需求计划暂停开发 (Issue #9)





 
APTV tvOS版本已上线Testflight，又需要参加测试的可以加tg群联系
