### ISSUE TITLE
买你们app了 问你们问题不回复 还踢我 就是这样的售后服务吗

### ISSUE THREAD

**Issue by wongharlan** [Kimentanm/aptv#99]

**Comment by Kimentanm** [comment]
请问你的tg名字叫什么？

**Comment by Kimentanm** [comment]
下面这个是你吧
1. 首先你问的问题是直播源的问题，与App本身无关，只有直播源的作者可以回答你，我也不知道怎么回答你
2. 我不是一天24小时都在群里，不能回复群里的每个问题，有问题请给我发邮件或者像现在这样在github创建issue
3. 最后，不断地在群里刷屏，是你被封禁的根本原因

<img width="624" alt="image" src="https://github.com/user-attachments/assets/5d918951-a5d3-4d72-8d14-5d40ca439254">
